### ISSUE TITLE
[Infra] viewing inventory and potion loot

### ISSUE THREAD

**Issue by Weeblin** [SOMAS2022/SOMAS2022#102]
In the view.go, it currently seems to give viewing to other agents' stats, does viewing inventory&loot pool also going to be part of view.go, or are they somewhere else?

**Comment by neeldug** [comment]
> @neeldug we're probably going to have to refactor how agent information is passed to agents bc agent.go is not looking good (and I'm struggling to pass data through to Random 😢)

Hmm, I think you might be right albeit if we pass it through BaseAgent with getters (it could be alright) with agent having some setters such that we can change fields from main thread using the setter but agents cannot.

**Comment by Weeblin** [comment]
> Inventories are meant to be private so that will most likely have to go in `BaseAgent` - doesn't make too much sense to decouple it from there im and that's how we've been doing it so far.
> 
> Loot pools probably makes sense to be put in View (as immutible lists see #100) but with views you have to be careful to make sure it gets updated for the agents.
> 
> @neeldug we're probably going to have to refactor how agent information is passed to agents bc agent.go is not looking good (and I'm struggling to pass data through to Random 😢)

Sorry 😂 I mean the shield and weapon loot not the inventory in general, and also in-hand inventory, those are to be made visible to agents. btw is it okay to make a message payload structure to them first for now so that agent teams can have those interfaces for writing their agents?

**Comment by neeldug** [comment]
> Sorry 😂 I mean the shield and weapon loot not the inventory in general, and also in-hand inventory, those are to be made visible to agents. btw is it okay to make a message payload structure to them first for now so that agent teams can have those interfaces for writing their agents?

Yeah, so afaik, the agents should be allowed to see any agents' current in-hand weapon/shield but not anyone else's inventory except their own. With regards to making the message structure, feel free, it should end up implementing on top of #114 , using the `LootInform` and `LootRequest` interfaces.
