### ISSUE TITLE
Refactor Agent Views

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#105]
> Shall we do that in a new refactoring issue along with removing the slice from the global state and either:
> 
> * Adding viewing to the potion pool by reading results from the output of `AllocateLoot`?
> * Update `viewing` to potion loot in the `AllocateLoot`

Yep - I think that makes sense, a separate PR makes sense for this. I had some other changes to Loot that we can bundle in too, namely I think we're calling `toView()` too often, and passing the view when we no longer need to.

_Originally posted by @neeldug, @Weeblin in https://github.com/SOMAS2022/SOMAS2022/issues/98#issuecomment-1336249571_

**Comment by neeldug** [comment]
Still has some stuff regarding adding potions and such available to agents, (perhaps through view or maybe elsewhere). FWIW I think passing it as an argument makes sense here since it's only relevant per-stage, i.e. from level to level the loot drops don't affect global state until being picked up.
