### ISSUE TITLE
Add math for loot 

### ISSUE THREAD

**Issue by Noanan** [SOMAS2022/SOMAS2022#124]
c.f. overview doc ver 2

**Comment by Noanan** [comment]
> Just realised this but in PR #134 , we seem to reseed the random number generator on every call to `delta()`, this probably isn’t correct, right? @Noanan

Good point, I'm not 100% sure. Our doc just mentions that its random without specifying if it is constant, so I just assumed that it should be random everytime. @BusterBlack could you confirm if that is the case or not and I will change it accordingly.

**Comment by BusterBlack** [comment]
def should be random every time... I can't remember 100% how it works, but i believe that if you don't re-seed, it will repeat the same sequence of random numbers... though i could be wrong.

**Comment by neeldug** [comment]
> def should be random every time... I can't remember 100% how it works, but i believe that if you don't re-seed, it will repeat the same sequence of random numbers... though i could be wrong.

You only need to seed once at the start, it’s written in the rand package docs.
