### ISSUE TITLE
What is the intended way to run main.go?

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#13]
A bit frustrated about how to run main.go

```bash
git clone git@github.com:SOMAS2022/SOMAS2022.git
cd SOMAS2022
cd pkg/infra
go run main.go
```
The above actions would result in an error:

```
2022/11/10 16:51:08 No .env file located, using defaults
exit status 1
```

This is because `godotenv.Load()` search `.env` in cwd by default, while our `.env` in located in the root directory. 
https://github.com/SOMAS2022/SOMAS2022/blob/1b7277ede74df3db121298f7b2880cfe07d63ae5/pkg/infra/main.go#L95

Also, maybe we should add a quick start section in README?

**Comment by neeldug** [comment]
`go build` in `pkg/infra` and then run the executable in the root, or we set were godotenv.Load() pulls from should be the typical way to run it.

**Comment by Razvan00Rusu** [comment]
The Makefile from #15 and #20 make this easier. If someone wants to add this to the README they should.
