### ISSUE TITLE
[Infra] New fight resolution form

### ISSUE THREAD

**Issue by Weeblin** [SOMAS2022/SOMAS2022#144]

**Comment by neeldug** [comment]
And another one I'm wondering, as leaders' channels seem to want leaders to return thresholds for infra to impose individual agent's actions, while our current return is still a map of individual actions, is this something we need to change soon?
https://github.com/SOMAS2022/SOMAS2022/blob/b066dba34bf293ab15abf3d7ba4d6108b3d96866/pkg/infra/game/agent/strategy.go#L34
 Many may have written their algorithm based on action map.

_Originally posted by @Weeblin in https://github.com/SOMAS2022/SOMAS2022/issues/143#issuecomment-1341800226_
      
Is this essentially the difference in that the FightResolution call shouldn't send leaders the proposal with the most votes, but instead the map of the calculated decisions based on the proposal, because if so this is a minor adjustment?

**Comment by Weeblin** [comment]
> 

I think at least the proposals that leader receive/ distribute for voting has to be changed to threshold based. I am not sure if leader then return proposal id or

**Comment by neeldug** [comment]
> I think at least the proposals that leader receive/ distribute for voting has to be changed to threshold based. I am not sure if leader then return proposal id or threshold criteria as fight resolution(so leader may be able to return a proposal in non of the proposals in voting).

Currently the proposal the leader receives the threshold from the winning proposal, so I don’t think that’s too much of an issue, I.e. the leader receives the rules from imposition and then generates a map of id’s to actions — however this could be changed to rules instead?

**Comment by neeldug** [comment]
> > > I think at least the proposals that leader receive/ distribute for voting has to be changed to threshold based. I am not sure if leader then return proposal id or threshold criteria as fight resolution(so leader may be able to return a proposal in non of the proposals in voting).
> > 
> > 
> > Currently the proposal the leader receives is the threshold from the winning proposal, so I don’t think that’s too much of an issue. I.e. the leader receives the rules from imposition and then generates a map of id’s to actions — however this could be changed to rules instead?
> 
> If this is leaders that generate an action map then there probably opens up a new spot for agents to deceit, for example, the leader deceit the action imposition to not refer to the winning rules. If it returned rules to the infra and lets infra to map it to actions, there still are chances the leader returns dictated rules...unless returns a proposal id... hmmm....is this meant for deceit and credit control for the agent team side?

Yeah, less so deceit more so as a leader with imposition you gain Imperial power to determine the course of the these rounds if elected with these powers.

**Comment by Weeblin** [comment]
btw is the fighting proposal put on vote anonymous? I can't seem to find where the agent is able to view which agent proposed this proposal.

**Comment by Weeblin** [comment]
I also wonder what the threshold rules would look like, for example, (attack lower bound)+(defend lower bound)+(coward superabound)? or  (attack lower range)+(defend lower range)+(coward range) or discard coward criteria, any agent that doesn't meet attack/defend goes coward by default?

**Comment by neeldug** [comment]
> btw is the fighting proposal put on vote anonymous? I can't seem to find where the agent is able to view which agent proposed this proposal. Is the winning proposal going to be available to all agents as well?

Yeah — so iirc the agent can see the _proposer_’s ID when receiving the voting part but as of now the winning proposal isn’t available — just the proposed action they should take.

**Comment by neeldug** [comment]
> I also wonder what the threshold rules would look like, for example, (attack lower bound)+(defend lower bound)+(coward superabound)? or (attack lower range)+(defend lower range)+(coward range) or discard coward criteria, any agent that doesn't meet attack/defend goes coward by default?

Yep — exactly, an example to go by is the random agent where it always uses these set rules to decide on who should attack/defend/cower and the default action in fights is cower, whereas with loot the default action is to take nothing.
