### ISSUE TITLE
Dispute Resolution

### ISSUE THREAD

**Issue by neeldug** [SOMAS2022/SOMAS2022#157]
- [ ] Work out what to do here, and when
- [ ] Implement it

**Comment by 1rre** [comment]
We could come up with a punishment system, ranging from "your vote doesn't count for N turns", to "we're going to force you to not cower for N turns" (ie forcibly stopping them from cowering regardless), if it happens after they defect

It could be more interesting to do this before defection though, where an agent broadcasts that they intend to defect - we could then try and resolve it peacefully by finding another agent doing their desired action to swap with, or by just saying "ok". This could be broadcast to everyone to help people with social capital scores - basically saying "this agent is throwing a tantrum to get their way" and letting them adjust accordingly.

**Comment by Razvan00Rusu** [comment]
How are these punishments going to be decided though? Based on severity? Based on what the leader wants? Based on what the agents think it should be? Should it be enforced (probably should like going to prison)?
