### ISSUE TITLE
workflow `run_game` fail to work

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#16]
https://github.com/SOMAS2022/SOMAS2022/blob/77533eb6bbf8fad5d42ec7c8e0efb4e3184e3e34/.github/workflows/run_game.yaml#L36

This command does not work in root directory. 

```
stat main.go: no such file or directory
```

![image](https://user-images.githubusercontent.com/34958528/201205092-21bf01e2-be00-46c4-a9b7-ffaa03364416.png)

**Comment by 0x6770** [comment]
I added a `go.work` file in #15, it enables `go run infra` in root directory. After #15 been merged, we should be able to fix this issue by using `go run infra ${{ matrix.agents }}` to replace https://github.com/SOMAS2022/SOMAS2022/blob/77533eb6bbf8fad5d42ec7c8e0efb4e3184e3e34/.github/workflows/run_game.yaml#L36

**Comment by EdvardJSHolen** [comment]
Think this issue has been fixed with #22
