### ISSUE TITLE
Weapon / Shield isn't assigned

### ISSUE THREAD

**Issue by TIE666** [SOMAS2022/SOMAS2022#164]
I tried on both the random agent and our team's, seems the weapon / shield isn't assigned properly.

![image](https://user-images.githubusercontent.com/47147482/207511270-39f24395-5df6-494f-8029-609165a81633.png)

Printing ID of the weapon in use is all zeros.

![image](https://user-images.githubusercontent.com/47147482/207511553-cfbcb52f-c641-4bab-86e2-eb1088ab5ec7.png)

This result in the maxAttack always stay at 2000 (number of agent * their base attack), even at level 17, where the agents suppose to have at least some weapon to use.

Or it could be some mis-implementation on my side, if anyone could help, big thanks.

**Comment by neeldug** [comment]
👀

**Comment by neeldug** [comment]
Have had a look into it, random agent shouldn't end up picking up any loot since there are no loot proposals made and they all ask for an empty list of weaponry, I'll double check to make sure the infra does correctly handle allocation when proposals are met but afaik it should be functioning.

**Comment by neeldug** [comment]
```go
loot := baseAgent.Loot()
	weapons := loot.Weapons().Iterator()
	shields := loot.Shields().Iterator()
	hpPotions := loot.HpPotions().Iterator()
	staminaPotions := loot.StaminaPotions().Iterator()

	builder := immutable.NewSortedMapBuilder[commons.ItemID, struct{}](nil)

	for !weapons.Done() {
		weapon, _ := weapons.Next()
		if rand.Int()%2 == 0 {
			builder.Set(weapon.Id(), struct{}{})
		}
	}

	for !shields.Done() {
		shield, _ := shields.Next()
		if rand.Int()%2 == 0 {
			builder.Set(shield.Id(), struct{}{})
		}
	}

	for !hpPotions.Done() {
		pot, _ := hpPotions.Next()
		if rand.Int()%2 == 0 {
			builder.Set(pot.Id(), struct{}{})
		}
	}

	for !staminaPotions.Done() {
		pot, _ := staminaPotions.Next()
		if rand.Int()%2 == 0 {
			builder.Set(pot.Id(), struct{}{})
		}
	}

	return *builder.Map()
```

Seemed to have worked with regards to adding loot, feel free to reopen if there are any further issues.

**Comment by TIE666** [comment]
I found what might be the cause, for shield actually.

In the state.go file, the BonusDefense is using weapon instead of shield.

![image](https://user-images.githubusercontent.com/47147482/207766051-a558061f-c081-436c-adf8-85faf4ce0651.png)

If you could update that on Main please.
