### ISSUE TITLE
Can't access rules properly in proposals

### ISSUE THREAD

**Issue by thl19git** [SOMAS2022/SOMAS2022#165]
When trying to implement HandleFightProposal (or HandleLootProposal), I'm unable to access the 'condition' and 'action' fields of the Rule type.

E.g. given `proposal` of type `message.Proposal[decision.FightAction]`:

```
iterator := proposal.Rules().Iterator()
for !iterator.Done() {
    rule, _ := iterator.Next()
    condition := rule.condition
}
```

This gives the error - rule.condition undefined (type proposal.Rule[decision.FightAction] has no field or method condition).

Is this an issue with infra or is there some other way we are supposed to look at the rules within proposals?

**Comment by neeldug** [comment]
> When trying to implement HandleFightProposal (or HandleLootProposal), I'm unable to access the 'condition' and 'action' fields of the Rule type.
> 
> E.g. given `proposal` of type `message.Proposal[decision.FightAction]`:
> 
> ```
> iterator := proposal.Rules().Iterator()
> for !iterator.Done() {
>     rule, _ := iterator.Next()
>     condition := rule.condition
> }
> ```
> 
> This gives the error - rule.condition undefined (type proposal.Rule[decision.FightAction] has no field or method condition).
> 
> Is this an issue with infra or is there some other way we are supposed to look at the rules within proposals?

Will take a look but a getter should be available via `rule.Condition()`
