### ISSUE TITLE
[infra/math] Game damage bug(?) 

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#18]
> > There is a really weird bug with the current implementation as the stamina drain effectively causes the entire cohort of agents to consider cowering together which results in them gaining more health than the monster deals, resulting in an infinite loop of healing more damage than that which is death by the monster.
> 
> Sounds like a feature not a bug to me 😎 LGTM

It ends up cycling between these quite often, something to definitely look into, since it's not a race related bug and instead some game mechanic bug with the split damage turning out to be tiny.

<img width="286" alt="Screenshot 2022-11-11 at 00 07 22" src="https://user-images.githubusercontent.com/5161147/201232069-fcf5b8f4-1107-4c7b-8189-dc3af4d7d586.png">
<img width="228" alt="Screenshot 2022-11-11 at 00 07 32" src="https://user-images.githubusercontent.com/5161147/201232071-8e6c13b0-6084-4052-a5ae-27090ef15387.png">

_Originally posted by @neeldug in https://github.com/SOMAS2022/SOMAS2022/issues/17#issuecomment-1311063797_

Created an issue so we have a record of this...

**Comment by neeldug** [comment]
Currently FWIW through the debugger, the [`SplitDamage`](https://github.com/SOMAS2022/SOMAS2022/blob/d8d37fdb208c5baaae523cedf37da6710bb78a9b/pkg/infra/game/stage/fight/fight.go#L12) ends up being 1 in some runs, and the cowering rewards 1 health resulting in infinite runs, would highly recommend going through it with a debugger and set a breakpoint [here](https://github.com/SOMAS2022/SOMAS2022/blob/d8d37fdb208c5baaae523cedf37da6710bb78a9b/pkg/infra/main.go#L50-L52)...

**Comment by BusterBlack** [comment]
This issue should be resolved with the equation update...
