### ISSUE TITLE
[infra] MVP - Problems with creating multiple types of agents

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#21]
This issue contains high-priority issues for MVP regarding agent creation that should be solved ASAP.

- [x] ~~Two `agent` folders exist at the moment. One in `pkg/agent`, and one in `pkg/infra/game/agent`. A decision should be made where agents files should go.~~
- Decision Taken: Agents should go in `pkg/infra/game/agent` to be in the same package as infra - at least for now.

- [x] ~~The [instantiateAgent](https://github.com/SOMAS2022/SOMAS2022/blob/f9db2d4ecb4c3d87b6830585641ce73eaaa55be9/pkg/infra/main.go#L129) method in pkg/infra/main.go contains a for loop that spawns in agents. The problem [here](https://github.com/SOMAS2022/SOMAS2022/blob/f9db2d4ecb4c3d87b6830585641ce73eaaa55be9/pkg/infra/main.go#L140) is that each agent is given an id based on a position on the loop - works for one type of agent but as soon as you have more, agents will have conflicting IDs. ~~

 - Fixed and decision taken: Using UUIDs for agent ids as part of #25 

- [x] The loop mentioned in part 2 also loops over `AgentRandomQty` instead of each other type of agent.

- Fixed as part of #25 

- [ ] No current good/clear/type safe way of spawning in different types of agents other than 'random'. A short term hack could be an if / switch statement but hopefully we can come up with a better way.

- Fixed (kind-of) as part of #25 but might want to revist it later.

A few final points:
- I suggest we keep all MVP-related-agent-creation-problems in this issue so we can keep track of what we've done and what's left as we don't have a lot of time to fix them. 
- If anyone else has come across any issues put them here too.
- If anyone is tackling an issue in this thread, post a comment so people are aware that it's being worked on.

**Comment by 0x6770** [comment]
Maybe not the best way, but the simplest way I can think of to fix conflicting agent ID is to use a global counter in `instantiateAgent`, increment and assign its value to every new created agent.

**Comment by Razvan00Rusu** [comment]
Will close this issue as most of the problems have been resolved. They can be readdressed later after MVP if needed.
