### ISSUE TITLE
improve type for agent maps

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#31]
https://github.com/SOMAS2022/SOMAS2022/blob/989887fc612a633f51c41f0d4414d8bf974d165c/pkg/infra/main.go#L146-L147

The current agent maps use `uint` as key. Since we've changed agentID to uuid, should we change the key type to string or use array instead?

**Comment by Razvan00Rusu** [comment]
This seems pretty serious tbh. It should stay as a map but definitely strings now that we use uuids!
