### ISSUE TITLE
collect data/log for frontend

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#32]
Maybe we could add a script to store data/log to a remote database after each run? So that data/log can be collected regardless whether game is run locally, by Github actions or other ways.
 
Then the frontend cloud query from that database to display the information visually.

Personally I suggest to use Cloudflare R2, https://developers.cloudflare.com/r2/get-started/ it's serverless and has free tier (10GB should be enough for our use case).

**Comment by Razvan00Rusu** [comment]
Used MongoDB for initial implementation just to get something up and going quickly (Free cloud tier <= 5GB). Definitely not opposed to mitrating to something else later.

I'm not 100% convinced we need a full DB either but being able to query data seems like it could be useful.

I've not heard or used R2 before. From looking it up a bit it seems that it's just a store with no querying capabilites - functions such as `putBucket` and `listBuckets`. Is my understanding right?

**Comment by 0x6770** [comment]
yes, R2 is just a store, it need some wrapper to interface with clients. Mongoldb is good choice, this issue probably can be closed.
