### ISSUE TITLE
[infra] Resource allocation

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#38]
> I see. I realized I miss a few things from last infra meeting. Shall we start documenting these ideas/rules even just draft? Agent teams will need them to work out their strategy. I can help to doc them e.g.
> 
> * How to form a government/organize an election if needed
> * Are resources allocated randomly, based on some rules, or by elected leaders

Yep, that would be great since I think formalising it into a document would ensure everyone's up-to-date with regards to the direction of the gameplay. I think specifically, the governance/organisation will be a social construct that is unenforced by the game itself, so these messages and electorate system needs to be decided between the agent teams and we should standardise the message formats in order to aid this. In terms of the resource allocation, in some earlier discussions we had, we found it could be quite interesting if greedy agents could exist, i.e. stealing the maximum value items from the pool - however, essentially each agent could make a loot decision when it comes to the common pool resource after some p2p communication to choose how to distribute the loot, and in the case of a tie, i.e. a conflicting loot choice between multiple agents, this would be broken randomly and it would be known to all agents who ended up receiving what loot in order to identify who's a bad actor.

_Originally posted by @neeldug in https://github.com/SOMAS2022/SOMAS2022/issues/36#issuecomment-1312597696_

**Comment by 0x6770** [comment]
Consider the simplest case where we have 3 agents A, B and C, and 100 HP for them to share.

| Agent | HP left | request |
|-------|---------|------|
|     A |      80 |   50 |
|     B |      50 |   50 |
|     C |      20 |  100 |

How should the game response to these request?

A few methods I can think of:
1. First come first served
   A and B will both get 50 HP, C will get 0
2. Send HP based on their request
   e.g. $$\text{HP obtained}_i = \frac{\text{HP requested}_i}{\sum{\text{HP requested}_i}} \times \text{HP available}$$
   A, B and C will get 25, 25 and 50 HP
4. Ignore their request, send HP to them based on their HP left
   e.g. $$\text{HP obtained}_i = \frac{100 - \text{HP left}_i}{\sum{(100 - \text{HP left}_i)}} \times \text{HP available}$$ 
   A, B and C will get 13.3, 33.3 and 53.3 HP
3. Let agents vote what allocation method to use. Or use a weighted mix of the above based on ranked voting. 

Please feel free to left comment or add your proposal.

**Comment by 0x6770** [comment]
Another thing yet been decided is, do we want the resources to be discrete or continuous? 

i.e. 
Do we generate
1. two list of items with HP or SP OR
2. two numbers, total_HP and total_SP

to share between agents?

**Comment by neeldug** [comment]
> Consider the simplest case where we have 3 agents A, B and C, and 100 HP for them to share.
> 
> Agent	HP left	request
> A	80	50
> B	50	50
> C	20	100
> How should the game response to these request?
> 
> A few methods I can think of:
> 
> 1. First come first served
>    A and B will both get 50 HP, C will get 0
> 2. Send HP based on their request
>    e.g. HP obtainedi=HP requestedi∑HP requestedi×HP available
>    A, B and C will get 25, 25 and 50 HP
> 3. Ignore their request, send HP to them based on their HP left
>    e.g. HP obtainedi=100−HP lefti∑(100−HP lefti)×HP available
>    A, B and C will get 13.3, 33.3 and 53.3 HP
> 4. Let agents vote what allocation method to use. Or use a weighted mix of the above based on ranked voting.
> 
> Please feel free to leave comment or add your proposal.

I think proposal 1 won’t be feasible easily since ordering these would be difficult without some explicit time stamping — but this causes unfairness when scheduling is involved. I think the others make sense, initially, I figured we’d maximise the acceptance and in the case of conflicting decisions (I.e. loot allocation) we randomly allocate. But these all are valid, perhaps worth getting input from agent teams.

**Comment by neeldug** [comment]
> Another thing yet been decided is, do we want the resources to be discrete or continuous?
> 
> i.e. Do we generate
> 
> 1. two list of items with HP or SP OR
> 2. two numbers, total_HP and total_SP
> 
> to share between agents?

I think either works but initially we were planning proposal 1, but the latter invites more creative allocations (but perhaps makes the burden of allocation too easy).

**Comment by Razvan00Rusu** [comment]
Something to keep in mind about this discrete vs continuous debate - (I think) we don't want agents to get into discussions about who should get the extra 0.00000000214 HP so from that point of view if we chose to go with continuous values they should at be quantised in some way (e.g. an agent will only request in 0.5HP points).

**Comment by Razvan00Rusu** [comment]
Also in terms of voting on infra vs P2P I think similar immutability concerns might arise if we trust the agents to vote entirely amongst themselves (agents might change votes etc) - unless we have a way to address this we could use infra as a 'polling station' of sorts where vote integrity is ensured and relayed back to the agents - but then the agents interpret those results as they wish.

**Comment by 0x6770** [comment]
> Also in terms of voting on infra vs P2P I think similar immutability concerns might arise if we trust the agents to vote entirely amongst themselves (agents might change votes etc) - unless we have a way to address this we could use infra as a 'polling station' of sorts where vote integrity is ensured and relayed back to the agents - but then the agents interpret those results as they wish.

By interpret, do you mean agents can use different methods to decide who is the winner given the same votes from infra?

**Comment by Razvan00Rusu** [comment]
Not really, I think the voting method will be decided by the agents anyway? What I meant is that if the voting wasn't regulated by infra then it could be subject to agents essentially rewriting other agent's votes. However, after speaking with Neel about this I don't think it's as big if an issue as I originally thought.

**Comment by Razvan00Rusu** [comment]
Closing as this conversation is outdated (time flies in SOMAS). If anything here needs to be continued just open a new issue : )
