### ISSUE TITLE
100% Cower

### ISSUE THREAD

**Issue by BusterBlack** [SOMAS2022/SOMAS2022#54]
`fight.DealDamage` is only called `if globalState.MonsterHealth > 0 && shieldSum < globalState.MonsterAttack` OR `if coweringAgents == uint(len(agentMap))`.
therefor, `fight.DealDamage` is only called if the agents don't kill the monster in 1 round. 

When this happens, the next round has 100% cowering. Every-time. Resulting in a number of rounds until the game is lost. I'm not sure why every agent is forced to cower immediately after the first and only call of `fight.DealDamage`.

Please note: multiple rounds can happen on the same level without this happening, because if `shieldSum > globalState.MonsterAttack` then `fight.DealDamage` isn't called. 

(^^ the first 'if' statement is an addition that solves the monsters high attack value caused by using unsigned ints with a neg result)

**Comment by BusterBlack** [comment]
ive solved this

**Comment by BusterBlack** [comment]
when re-assigning agent states in dealDamage it ignored stamina, which was then reset to 0... so i just added stamina to it and it wroked

**Comment by neeldug** [comment]
> when re-assigning agent states in dealDamage it ignored stamina, which was then reset to 0... so i just added stamina to it and it wroked

Could you open a PR with this change such that it can get merged? Shouldn't require too much effort.

**Comment by BusterBlack** [comment]
will do tonight. can't right now.

**Comment by BusterBlack** [comment]
sorry it hasn't been done already

**Comment by neeldug** [comment]
No worries - will merge asap since review should be minor.
