### ISSUE TITLE
Deal Damage To All Agents (Not Just Those Who Fight/Defend)

### ISSUE THREAD

**Issue by BusterBlack** [SOMAS2022/SOMAS2022#55]
`fight.DealDamage()` is called with `globalState.AgentState` as an argument. This is used to calculate `splitDamage` and then assign damage to each agent. At the moment, this is done to all agents irrespective of their fight decision.
Adding an agent parameter `Decision` would then allow iterations to check the decision and then only apply damage if `decision != cower`. This would also require `fight.DealDamage()` to be passed the number of cowers for the correct `splitDamage` calculation.

**Comment by Razvan00Rusu** [comment]
Just to be clear - the monster damage would be split only between agents that _don't_ cower? If so I can do this, should be a small fix.

**Comment by BusterBlack** [comment]
yeah, thats an easy fix... but only applying the damage to the agents that fight is a bit harder i think
