### ISSUE TITLE
Add Request Response Messaging

### ISSUE THREAD

**Issue by neeldug** [SOMAS2022/SOMAS2022#56]
- [x] Create some type structure to route messages based on their type (Request vs. Information)
- [x] Support message handlers for both with auto-response from infra to Request messages
- [x] Add to the API

**Comment by max-wickham** [comment]
I've started working on this today, not sure if @man-like-vinny you've started looking as well?

**Comment by max-wickham** [comment]
I've started refactoring how messages work and put it on a branch called addrequests,

**Comment by neeldug** [comment]
> I've started refactoring how messages work and put it on a branch called addrequests,

Could you start a draft PR and link it to say it fixes this issue?

**Comment by max-wickham** [comment]
Yeah theres loads of problems that I don't think I should mess with till I have checked with you how some stuff is working

**Comment by max-wickham** [comment]
but yeah I think fundamentally this fixes a few issues
