### ISSUE TITLE
Support P2P trade rounds

### ISSUE THREAD

**Issue by neeldug** [SOMAS2022/SOMAS2022#58]
- [x] add inventory system and item struct #80 
- [ ] Leverage Request Response messaging enabled by #56 to handle P2P trading
- [x] Validate trades server-side and ensure validity of trades
- [x] Respond to trade participants with trade activity on state modification

**Comment by 0x6770** [comment]
Seems like this issue is no longer blocked? @neeldug

**Comment by neeldug** [comment]
Blocked by #72 , probably need inventories and some weapon id system before work can occur here.

**Comment by neeldug** [comment]
Unblocked - forgot to fix this one
