### ISSUE TITLE
Initial Support to Governance

### ISSUE THREAD

**Issue by neeldug** [SOMAS2022/SOMAS2022#59]
It would be nice to add a governance round prior to each level where some form of governance is established and updated within the infrastructure's state, given that governance's institutional power hasn't be established yet, an initial headway could be made here, albeit election methodology hasn't been established either...
Todo: 
- [x] Add election round (some dummy election could work here for now)
- [x] Support modular election systems (potentially future PR?)
- [ ] Embed modular institutional power - i.e. power over group decisions or just suggestions for: fights, loot & hp pool (future PR?)

**Comment by Razvan00Rusu** [comment]
Notes from the meeting today relating to governance:

- Agents will campaign for election with a set of imposition:
- Agents can choose whether they want power over fight decisions, loot decisions or both
- If the leader is given this power, they have control over group action in the round - but can still take advice from the floor.
- If the leader does not have this power but is still elected, then they facilitate a vote of the agents and the most popular proposal will be take.
- Along with this, the agent must also decide how long it will be in power for (in no. of levels) and the threshold % reached to be evicted from power.
- If elected, the  agent is in power until its term is over or the % percentage to be removed from power is reached.

Someone correct me if I've forgotten or missed anything.

**Comment by Razvan00Rusu** [comment]
From my understanding no. Each agent would have a `manifesto` consisting of all of this information, and that is what the agents vote on.

So we would just have a voting round at the start of each round I think. And then we didn't really discuss this in the meeting to be honest but based on the original diagram we would have 2 discussion rounds, one at the start (for fight action) and one at the end for loot distribution etc. These would both be done through the leader and the leader needs to have power over the floor (i.e. who is allowed to put forward proposals to the group). 

This last part on when the discussions happen I'm not 100% sure about, @neeldug @BusterBlack what do you think?

**Comment by 0x6770** [comment]
I see, but we still have at least two different ways to process these collected `manifesto`.

After find out who is the new leader, decide what power to be given and term length

1. based on those `manifesto` which vote for the new leader
OR 
2. based on all collected `manifesto`

**Comment by Razvan00Rusu** [comment]
So for that I think the power given is based on the `manifesto` they were elected on.

**Comment by BusterBlack** [comment]
vote of 'no confidence' a the end of each level. If threshold reached, elect new leader before moving to next level. 

Discussion at beginning of each round for fight allocation/risk analysis (before proposal) AND at the end of each level for Loot distribution

**Comment by 0x6770** [comment]
yeah, I also have a question about term limit, if we let agents 
1. decide term limit at election
2. decide if they want to choose a new leader in next round

Isn't this equivalent to having election at every level? which might even be simpler to implement.

**Comment by neeldug** [comment]
> yeah, I also have a question about term limit, if we let agents
> 
> 1. decide term limit at election
> 2. decide if they want to choose a new leader in next round
> 
> Isn't this equivalent to having election at every level? which might even be simpler to implement.

Yeah I mentioned this at the meeting too, I was still a little hazy as to why we need a term limit/vote of no confidence if you can opt to re-elect the same leader.

**Comment by BusterBlack** [comment]
The reason for the `manifesto` was to allow agents to vote based on some parameters, besides just the agent identification. This isn't so much, "what power they have", rather "Which powers they will choose to wield". It adds another layer to the game, which i like. 
As for the term/threshold decision. This allows leaders to stay in the roll for more than 1 level. A new election every time would make it hard to be re-elected, as every agent would consider all other agents in the election. Having multiple levels in charge allows more interesting leader implementations from agent teams. Also, no-confidence votes are much quicker (binary) than leadership votes (all-agents considered)

**Comment by BusterBlack** [comment]
as for vote facilitation...

The leader grants access to the floor for agents to make a proposal. This proposal is then voted on. If it passes, one of two things happens.
- if leader has fight power - the leader can change the agreed proposal as they wish, on an agent by agent basis, before sending it to the main thread
- if the leader does not have the fight power - the infrastructure locks the proposal decisions. (the leader essentially passes the proposal to the main thread without alteration)

This example is for the fight decisions. @neeldug - is this what we were thinking? or something similar w.r.t leader -> infra relationship on proposals.

**Comment by neeldug** [comment]
> as for vote facilitation...
> 
> The leader grants access to the floor for agents to make a proposal. This proposal is then voted on. If it passes, one of two things happens.
> 
> * if leader has fight power - the leader can change the agreed proposal as they wish, on an agent by agent basis, before sending it to the main thread
> * if the leader does not have the fight power - the infrastructure locks the proposal decisions. (the leader essentially passes the proposal to the main thread without alteration)
> 
> This example is for the fight decisions. @neeldug - is this what we were thinking? or something similar w.r.t leader -> infra relationship on proposals.

Yep, this is essentially what I had taken it to mean, not sure if we're locking actions to agents to the proposal, (depends on if we want deceit)? But I think it's honestly fairly open to have two modes of operation with binding proposals and non-binding proposals?

**Comment by 0x6770** [comment]
> The reason for the `manifesto` was to allow agents to vote based on some parameters, besides just the agent identification. This isn't so much, "what power they have", rather "Which powers they will choose to wield". It adds another layer to the game, which i like. As for the term/threshold decision. This allows leaders to stay in the roll for more than 1 level. A new election every time would make it hard to be re-elected, as every agent would consider all other agents in the election. Having multiple levels in charge allows more interesting leader implementations from agent teams. Also, no-confidence votes are much quicker (binary) than leadership votes (all-agents considered)
> 
> This is what i took from everything

I see your point. However, despite the "no confidence" vote is binary, rational agents will still consider all other agents before they make "no confidence" votes, i.e. find a global optimal. Plus, if we choose leader by majority, it's very likely to have the new leader be evicted in the same level e.g. voted by 51%  agent in election, but some percentage of supporting agents regret.

**Comment by BusterBlack** [comment]
> > The reason for the `manifesto` was to allow agents to vote based on some parameters, besides just the agent identification. This isn't so much, "what power they have", rather "Which powers they will choose to wield". It adds another layer to the game, which i like. As for the term/threshold decision. This allows leaders to stay in the roll for more than 1 level. A new election every time would make it hard to be re-elected, as every agent would consider all other agents in the election. Having multiple levels in charge allows more interesting leader implementations from agent teams. Also, no-confidence votes are much quicker (binary) than leadership votes (all-agents considered)
> > This is what i took from everything
> 
> I see your point. However, despite the "no confidence" vote is binary, rational agents will still consider all other agents before they make "no confidence" votes, i.e. find a global optimal. Plus, if we choose leader by majority, it's very likely to have the new leader be evicted in the same level e.g. voted by 51% agent in election, but some percentage of supporting agents regret.

Votes are every level, so nobody can be deposed mid-level. Each agent should implement a 'satisfaction' rating w.r.t to the leader... this doesn't involve considering other options really. purely leader based. "am i happy with the way things are" - "no?" - then i vote to get rid of the leader. Now i can search for a new one. 

Also, since having a majority in this game will be v. hard... i think we agreed to go with a popular winner (i.e. whoever gets the most votes)

**Comment by 0x6770** [comment]
Consider the case we have 100 agents and start an election round, as you said, it might be very hard have an agent get more than 50 votes, so we assume there is Agent A which get most votes at the end, 20 votes. Thus, 80 agents do not favor agent A with their reasons, and we let all 100 agent to choose if they are happy with agent A. 

But yeah, I agree it will be interesting to see this will happen or not. And it will be a easy switch to force election at each level if we end up with the game effectively start a new election round for every level.

**Comment by BusterBlack** [comment]
yes, but voting for an agent to be leader and voting against the current leader and two different mechanisms. just because you didn't vote for the leader, doesn't mean your agent will be unsatisfied with their ruling. 
But you're right, a leadership election could take place every round... and that would be an interesting thing to report

**Comment by jl21518** [comment]
> The reason for the `manifesto` was to allow agents to vote based on some parameters, besides just the agent identification. This isn't so much, "what power they have", rather "Which powers they will choose to wield". It adds another layer to the game, which i like. As for the term/threshold decision. This allows leaders to stay in the roll for more than 1 level. A new election every time would make it hard to be re-elected, as every agent would consider all other agents in the election. Having multiple levels in charge allows more interesting leader implementations from agent teams. Also, no-confidence votes are much quicker (binary) than leadership votes (all-agents considered)
> 
> This is what i took from everything

Does it make sense to let agents propose their fight and allocation policies (the allocation system will in turn have to change to a leader oriented one) before getting elected? Not much information can be poached from the manifesto atm if it only entails how power is wielded.

**Comment by Razvan00Rusu** [comment]
> > The reason for the `manifesto` was to allow agents to vote based on some parameters, besides just the agent identification. This isn't so much, "what power they have", rather "Which powers they will choose to wield". It adds another layer to the game, which i like. As for the term/threshold decision. This allows leaders to stay in the roll for more than 1 level. A new election every time would make it hard to be re-elected, as every agent would consider all other agents in the election. Having multiple levels in charge allows more interesting leader implementations from agent teams. Also, no-confidence votes are much quicker (binary) than leadership votes (all-agents considered)
> > This is what i took from everything
> 
> Does it make sense to let agents propose their fight and allocation policies (the allocation system will in turn have to change to a leader oriented one) before getting elected? Not much information can be poached from the manifesto atm if it only entails how power is wielded.

It definitely could do. I think it would add an element of trusting the leader - do leaders deliver on what they said they would do? That being said I'm against going too specific and instead maybe opting for `Defensive`, `Moderate` and `Aggressive` for fighting and `Conservative`, `Moderate` and `Generous` for loot.
