### ISSUE TITLE
Refactor logging and methods

### ISSUE THREAD

**Issue by neeldug** [SOMAS2022/SOMAS2022#60]
> Something I've thought of literally just now, do you think the log method makes more sense in `BaseAgent` or `Agent`? Also in agent methods (in `RandomAgent` `HandleFightMessage`) do we need to pass in the `agent BaseAgent` param if this is available through `r RandomAgent`? This could probably be the scope for a seperate refactoring PR....

_Originally posted by @Razvan00Rusu in https://github.com/SOMAS2022/SOMAS2022/issues/53#issuecomment-1321214800_

**Comment by neeldug** [comment]
maybe also add a log here for fight? 
```suggestion
	case 1:
		agent.log(logging.Trace, logging.LogField{"bravery": r.bravery}, "Fight")

```

_Originally posted by @0x6770 in https://github.com/SOMAS2022/SOMAS2022/pull/53#discussion_r1027337205_

**Comment by man-like-vinny** [comment]
@giorgosvyronos hey, just to avoid any overlap of work. Have you committed any refactoring, or currently on specific refactoring? Thanks.

**Comment by giorgosvyronos** [comment]
@man-like-vinny I have not yet committed anything regarding this, I'm still experimenting locally so you can go ahead and commit anything you want on this if you have something working.

**Comment by man-like-vinny** [comment]
After looking at the both the agent and base agent scripts, it doesn't make sense to refactor the code to agent. The logging method is best kept in baseagent. The case is closed.
