### ISSUE TITLE
go.work file in root directory is breaking VSCode Intellisense

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#65]
As title, the `go.work` file in the root directory is breaking my VSCode intellisense (and a continous error appears at the bottom) - starts working again when I delete this file.

Raising this issue to see if this file is there for a reason - I'm not 100% sure what a go.work file does so don't want to create a PR to remove it without confirming : )

**Comment by 0x6770** [comment]
> As title, the `go.work` file in the root directory is breaking my VSCode intellisense (and a continous error appears at the bottom) - starts working again when I delete this file.
> 
> Raising this issue to see if this file is there for a reason - I'm not 100% sure what a go.work file does so don't want to create a PR to remove it without confirming : )

Does it break your go or ts related intelligence? Maybe you can post a log?

**Comment by antonypap** [comment]
Used to have this issue before, I think it has been fixed with formatting of go.work file in #48.

**Comment by Razvan00Rusu** [comment]
Ok for some reason my VSCode woke up today and decided to work which is nice. It now works on main and on the branch for #48 so should be all good. I think it was stuck in some sort of error state and messing around with the `go.work` file caused it to reset and fix itself.
