### ISSUE TITLE
[infra] loot allocation design

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#72]
I assume the current implementation of loot allocation is just as a placeholder. We can use this issue to plan out the design of actual loot allocation. 

If this has not been decided, perhaps we can start with the questions below,
1. What types of item can we get in the loot (and store in inventory)? 
   Currently we have potion for health point, shield for defense point and weapon for attack point, do we want items with a mix of HP, DP and AP? 
2. How many items of potion/weapon/shield can each agent have at the same time?
   From #68, it seems like each agent will have at least 2 items for each type. One visible to the public, the rest is stored in the inventory and is not visible to others. 
3. Or maybe we do not limit the number of item of specific type that a agent can hold, but limit the capacity of inventory so $n \ge \text{size}(\text{shields}) + \text{size}(\text{potions}) + \text{size}(\text{weapon})$ 
4. AS discussed in #38 , we probably want the value of these items to be quantised or integer based.
5. How do we allocate the loot? 
   Do we broadcast all available loot to all agents, let them choose want they want and randomly pick a winner if conflict happens? 
   If agent A and agent B both want `item 1`, and A get `item 1` eventually, will B have the chance to ask a new item?
   OR, do we adapt the voting based weighted allocation mentioned in the lecture? 
6. What kind of power do we want the leader to have over loot allocation? 
   Maybe we can let leader to solve conflict?

**Comment by BusterBlack** [comment]
Hey man, a lot of this has been discussed already. 

Equipment includes:
- potions (for HP and stamina)
- Weapons (for bonusAttack)
- Shields (for bonusDefense)

Average values of each will increase each level and will be set within a range. The number of each dropped by each monster is set at the beginning of the game as a percentage of `N` and will create an economy of scarcity. Agents can store them in the inventory (private) or equip them (public). 

The allocation method is via proposals and the leader reconciles any clashes. The list of item i guess will be broadcast to all agents (but this was never discussed)

If the leader is elected with the power to override loot, then they can. Otherwise, loot clashes are resolved randomly. 

Obviously none of this is implemented yet

**Comment by 0x6770** [comment]
> Hey man, a lot of this has been discussed already.
> 
> Equipment includes:
> 
>     * potions (for HP and stamina)
> 
>     * Weapons (for bonusAttack)
> 
>     * Shields (for bonusDefense)
> 
> 
> Average values of each will increase each level and will be set within a range. The number of each dropped by each monster is set at the beginning of the game as a percentage of `N` and will create an economy of scarcity. Agents can store them in the inventory (private) or equip them (public).
> 
> The allocation method is via proposals and the leader reconciles any clashes. The list of item i guess will be broadcast to all agents (but this was never discussed)
> 
> If the leader is elected with the power to override loot, then they can. Otherwise, loot clashes are resolved randomly.
> 
> Obviously none of this is implemented yet

Yes, some of you mentioned is covered in the your overview PDF, thanks for that PDF btw, but we still lack the detail of how loot allocation work, one month later. 

The point of this issue is to discuss the part that have not been decided yet (2, 3, 5), and record what have been decided in text (1, 4, 6). In the end, we still need to write down these rules in the report.

**Comment by BusterBlack** [comment]
i'm doing a new overview doc with all this now... the other PDF is wayyy out of date

**Comment by BusterBlack** [comment]
how i think it works is: all agents see the loot available and request access to a specific piece of equipment. any clashes at the end of the request round are resolved by random or the leader.

**Comment by BusterBlack** [comment]
1 equipment slot for weapon, 1 for shield, 1 for potion (which is consumed immediately) 
The inventory is currently limitless and can hold any piece of equipment privately. (currently)

**Comment by 0x6770** [comment]
A further question on equipment slot, can an agent choose to not use any equipment e.g. weapon despite it has some weapon in its inventory?

**Comment by BusterBlack** [comment]
i guess so yes... i think every agent should have a method to wield equipment or put it in the inventory

**Comment by 0x6770** [comment]
> i guess so yes... i think every agent should have a method to wield equipment or put it in the inventory

This only happen before fight, right?

**Comment by BusterBlack** [comment]
i think so yes. before every fight round would be the time to do it
