### ISSUE TITLE
[infra] add inventory and loot item id 

### ISSUE THREAD

**Issue by Weeblin** [SOMAS2022/SOMAS2022#80]
Blocked by #72 , probably need inventories and some weapon id system before work can occur here.

_Originally posted by @neeldug in https://github.com/SOMAS2022/SOMAS2022/issues/58#issuecomment-1327931082_

**Comment by Weeblin** [comment]
Does the agent also wield one potion from the inventory that is visible to other agents?

**Comment by Razvan00Rusu** [comment]
> Does the agent also wield one potion from the inventory that is visible to other agents?

No I don't think so. As far as I know, potions are consumed immediately. Only shields and weapons are kept in the inventory.

@BusterBlack is this correct 👀?
