### ISSUE TITLE
[election] manifesto selection

### ISSUE THREAD

**Issue by 0x6770** [SOMAS2022/SOMAS2022#82]
https://github.com/SOMAS2022/SOMAS2022/blob/d7bc239808fb4736ea1d06d8783d5d5cd3c8c5ea/pkg/infra/game/stage/election/election.go#L55-L56

https://github.com/SOMAS2022/SOMAS2022/blob/d7bc239808fb4736ea1d06d8783d5d5cd3c8c5ea/pkg/infra/game/decision/decision.go#L22-L27

https://github.com/SOMAS2022/SOMAS2022/blob/d7bc239808fb4736ea1d06d8783d5d5cd3c8c5ea/pkg/infra/game/decision/decision.go#L45-L47

In the current implementation, the game uses leader's manifesto to set `termLength` and `overthrowThreshold`. And it allows agents to set any value for these two fields.

This setting encourages agents to set large if not infinite `termLength` and `overthrowThreshold` to protect its position if it becomes leader.

**Comment by Razvan00Rusu** [comment]
I think this might not actually be the case. Once the election has taken place, a copy is made of the manifesto to be stored in `globalState` and the amount of rounds left in a leader's term is maintained directly in the game loop.

```go
electedAgent, manifesto, percentage := election.HandleElection(globalState, *agentMap, decision.VotingStrategy(gameConfig.VotingStrategy), gameConfig.VotingPreferences)
termLeft := manifesto.TermLength()
globalState.LeaderManifesto = manifesto
globalState.CurrentLeader = electedAgent
```

Whilst it's true that, in fact, any agent can change their manifesto after/in-between election periods, there is no benefit of doing so - the copy in `globalState` should be referenced - not the agent's.

**Comment by 0x6770** [comment]
Also, it feels like this line might cause division by zero if all agent abstain?

https://github.com/SOMAS2022/SOMAS2022/blob/d7bc239808fb4736ea1d06d8783d5d5cd3c8c5ea/pkg/infra/main.go#L150

**Comment by Razvan00Rusu** [comment]
> Also, it feels like this line might cause division by zero if all agent abstain?
> 
> https://github.com/SOMAS2022/SOMAS2022/blob/d7bc239808fb4736ea1d06d8783d5d5cd3c8c5ea/pkg/infra/main.go#L150

This is true... 🤔 Will add a fix to this in a refactoring PR I'm currently working on.

**Comment by 0x6770** [comment]
> I think this might not actually be the case. Once the election has taken place, a copy is made of the manifesto to be stored in `globalState` and the amount of rounds left in a leader's term is maintained directly in the game loop.
> 
> ```go
> electedAgent, manifesto, percentage := election.HandleElection(globalState, *agentMap, decision.VotingStrategy(gameConfig.VotingStrategy), gameConfig.VotingPreferences)
> termLeft := manifesto.TermLength()
> globalState.LeaderManifesto = manifesto
> globalState.CurrentLeader = electedAgent
> ```
> 
> Whilst it's true that, in fact, any agent can change their manifesto after/in-between election periods, there is no benefit of doing so - the copy in `globalState` should be referenced, not the agent's.

oh, I mean this encourage agents to submit manifesto with large `termLength` and `overthrowThreshold` in election.

**Comment by Razvan00Rusu** [comment]
But any manifestos will have to be voted on - regardless of what the leader sets it too afterwards. The leader cannot change its manifesto between elections without a vote (well it can but with no impact on the game). So if it gets elected with a large `termLength` and `overthrowThreshold` then that's fine and the choice of the agents.

Something to bear in mind is that `overthrowThreshold` is unsigned so it definitely can't be negative. If it is >= 100 the leader cannot be removed from power until the term ends (this + fight and loot imposition = dictatorship). 
(We should probably cap this so if agents set this to over 100, it reverts to 100).

It is likely that agents will punish manifestos that ask for too much power, for too long and for too high an overthrow threshold but there's nothing to stop these from being proposed.

Is this what you're referring to? Sorry if I'm misunderstanding 😅

**Comment by 0x6770** [comment]
I agree we shouldn't remove the possibility of dictatorship, but from result of the current simulation, an agent only needs < 5% to become leader. i.e. if an agent wants to become dictator has another one or two agents vote it randomly, we will have a dictator.

![image](https://user-images.githubusercontent.com/34958528/204602699-b16f5f73-98c2-4d92-a641-745ba94987a0.png)

**Comment by 0x6770** [comment]
Maybe we can restrict `overthrowThreshold` to some number < 100 e.g. 80 (and this should be configurable in `.env`)? Otherwise, we eliminate the possibility for agents to revolt.

**Comment by Razvan00Rusu** [comment]
I think the results seen in the game right now are because of two main factors:
1. The random agents are choosing randomly between the other 99 agents (with default config)
2. The default voting strategy (single choice plurality) just looks for the biggest majority (assuming a uniform distribution of the random votes each agent will get 1 vote, i.e. 1-2%.

Hoepfully with agents developed by teams, agents will be able to identify those who would make good leaders and a larger majority will be seen (fingers crossed).
Something else that does to be done is implementing some of the other voting strategies in `pkg/infra/game/stage/election/voting.go`. Some of these other voting strategies force a larger majority by having several rounds etc...
