### ISSUE TITLE
Parameterise overthrow threshold

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#94]
Maybe we can restrict `overthrowThreshold` to some number < 100 e.g. 80 (and this should be configurable in `.env`)? Otherwise, we eliminate the possibility for agents to revolt.

_Originally posted by @0x6770 in https://github.com/SOMAS2022/SOMAS2022/issues/82#issuecomment-1331057256_

**Comment by 1rre** [comment]
I disagree with this, as it should be up to the agents to realise how much of a commitment 100% overthrow threshold is

Imo either keep it as is or make it so the leader doesn't get to vote in a vonc
